#!/bin/bash
#SBATCH --job-name=analysis
#SBATCH -t 30:00
#SBATCH -p RM-shared
#SBATCH -N 1 --tasks-per-node=1
#SBATCH --mail-type=END,FAIL
set echo
set -x

cd $SLURM_SUBMIT_DIR
## Your commands here:
files="tests/test_data/scaling/scaling_1 tests/test_data/scaling/scaling_28"
basename=tests/test_data/scaling/scaling

rm ${basename}_log_list
for file in ${files[@]}
do
    echo ${file}.log >> ${basename}_log_list
done

namd_log_proc -p -l ${basename}_log_list

resubfiles=$(egrep -lir "sbatch" slurm*)
for file in $resubfiles
do
    rm $file
done
python -c "from md_utils import scaling; scaling.plot_scaling('$basename')"
