#!/bin/bash
#SBATCH --job-name=resubmit
#SBATCH -t 5:00
#SBATCH -p RM-shared
#SBATCH -N 1 --tasks-per-node=1
set echo
set -x

cd $SLURM_SUBMIT_DIR
## Your commands here:
files="/Users/xadams/PycharmProjects/md_utils/tests/test_data/scaling/scaling_1 /Users/xadams/PycharmProjects/md_utils/tests/test_data/scaling/scaling_28"
basename=/Users/xadams/PycharmProjects/md_utils/tests/test_data/scaling/scaling

for file in ${files[@]}
do
    if [ ! -f ${file}.log ]
    then
        echo "${file}.log does not exist"
        sbatch --begin=now+10minutes ${basename}_resubmit.job
        exit 1
    fi
done
sbatch --begin=now+10minutes ${basename}_analysis.job
