#!/bin/bash
#SBATCH --job-name=analysis
#SBATCH -t 30:00
#SBATCH -p RM-shared
#SBATCH -N 1 --tasks-per-node=1
#SBATCH --mail-type=END,FAIL
set echo
set -x

cd $SLURM_SUBMIT_DIR
## Your commands here:
files="/Users/xadams/PycharmProjects/md_utils/tests/test_data/scaling/scaling_1 /Users/xadams/PycharmProjects/md_utils/tests/test_data/scaling/scaling_28"

for file in ${files[@]}
do
	namd_log_proc -p -f ${file}.log
done
resubfiles=$(egrep -lir "sbatch" slurm*)
for file in $resubfiles
do
    rm $file
done
python -c "from md_utils import scaling; scaling.plot_scaling('$files',True)"
